### ISSUE TITLE
[Feature] Update PR default format.

### ISSUE THREAD

**Issue by rehohoho** [whizzmobility/models#10]
Our requirements are a little different. The current one takes very long to fill.

**Comment by rehohoho** [comment]
Closed with #19.

**Comment by rehohoho** [comment]
@MelvinFMQ can set the main branch to master? The change in PR template is not being reflected.

**Comment by MelvinFMQ** [comment]
done

**Comment by rehohoho** [comment]
Checked that the PR template is changed.
