### ISSUE TITLE
[Feature] Compatibility issue with phone GPU delegate

### ISSUE THREAD

**Issue by rehohoho** [whizzmobility/models#74]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this feature has not been requested already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/vision/beta

## 2. Describe the feature you request

Debug, find, fix the related ops that cause the compatibility issue.

## 3. Additional context

Add any other context about the feature request here.

## 4. Are you willing to contribute it? (Yes or No)
Yes

**Comment by rehohoho** [comment]
![delegate_compatibility](https://user-images.githubusercontent.com/57937231/125677416-2fbe9359-6bcc-4185-af0c-982ab51ada5f.png)

!#%!@^$#^# indeed. This will take some time to get ready for the GPU.

Using GPU with CPU fallback ~300ms, CPU only ~200ms. GPU is higher due to overhead when transferring buffers during fallbacks.

**Comment by MelvinFMQ** [comment]
Oh no!

**Comment by rehohoho** [comment]
Fixed on testing branch, the diff will conflict with #73.
