### ISSUE TITLE
[Misc] Go through an iteration of data-engine

### ISSUE THREAD

**Issue by CabooseExia** [whizzmobility/models#83]
Go through the data-engine and show how everything works. Add Ausie to repo too thanks

**Comment by rehohoho** [comment]
@anthonyfong100 @CabooseExia Check out https://github.com/whizzmobility/models/wiki/Running-the-models-pipeline, updated it.

**Comment by rehohoho** [comment]
I think this can be closed, as of 11/08.
https://whizzinc.sharepoint.com/sites/whizz/Shared%20Documents/data-engine/Recordings/Meeting%20in%20_Data%20Engine%F0%9F%93%8A%F0%9F%9A%A5_-20210811_170020-Meeting%20Recording.mp4
