### ISSUE TITLE
YOLO model cant train with batch size > 1

### ISSUE THREAD

**Issue by whizzscooters** [whizzmobility/models#88]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ ] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/...

## 2. Describe the bug
YOLO model is unable to be train with a batch size > 1

## 3. Steps to reproduce
/home/whizz/Desktop/models/official/vision/beta/configs/experiments/multitask/multitask_hardnet_detectorv1.yaml

## 4. Expected behavior
Allow training with batch size > 1

## 5. Additional context
<img width="1054" alt="Screenshot 2021-08-11 at 3 09 55 PM" src="https://user-images.githubusercontent.com/52654198/128999536-0c99b25f-3df9-46a4-8521-2e8be9b8360d.png">

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by rehohoho** [comment]
Looks related to
https://github.com/whizzmobility/models/blob/master/official/vision/beta/tasks/yolo.py#L224
https://github.com/whizzmobility/models/blob/master/official/vision/beta/dataloaders/yolo_input.py#L223

Had an issue before: #61.
